import { ToastContainer } from "react-toastify";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="p-6">
          {children}
          <ToastContainer />
        </div>
      </body>
    </html>
  )
};
